apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name:	hello-meta-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      meta-key: meta-val
  template:
    metadata:
      labels:
        meta-key: meta-val
    spec:
      containers:
        - name: metadatacontainer
          image: sunitparekh/metadata:v1.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5