apiVersion: v1
kind: Pod
metadata:
  name:	hello-nginx
spec:
  containers:
    - name: hello-nginx-app
      image: nginx
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html